"""
Django settings for passim project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import posixpath
import socket
import sys
from django.contrib import admin

hst = socket.gethostbyname(socket.gethostname())
bUseTunnel = False
# socket.setdefaulttimeout(None)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_NAME = os.path.basename(BASE_DIR)
WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../writable/database/"))
STEMMAC_DIR = os.path.abspath(os.path.join(BASE_DIR, "../stemmac/bin/"))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# print("Writable dir = [{}]".format(WRITABLE_DIR))

if "RU-passim\\writable" in WRITABLE_DIR:
    # Need another string
    WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../../writable/database/"))
elif "/applejack" in BASE_DIR:
    WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../writable/passim/database/"))

# Containerized Radboud Environment
if "/var/writable" in WRITABLE_DIR:
    WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../writable/database/"))
    PROJECT_NAME = os.path.basename(os.path.dirname(os.path.abspath(__file__)))
    STEMMAC_DIR = os.path.abspath(os.path.join(BASE_DIR, "stemmac/bin/"))

MEDIA_DIR = os.path.abspath(os.path.join(WRITABLE_DIR, "../media/"))
MEDIA_ROOT = os.path.abspath(os.path.join(WRITABLE_DIR, "../media/"))

PLUGIN_DIR = os.path.abspath(os.path.join(MEDIA_DIR, "plugin/"))

APP_PREFIX = ""
USE_REDIS = False
ADMIN_SITE_URL = ""
if "d:" in WRITABLE_DIR or "D:" in WRITABLE_DIR or "c:" in WRITABLE_DIR or "C:" in WRITABLE_DIR or bUseTunnel:
    APP_PREFIX = ""
    # admin.site.site_url = '/'
    ADMIN_SITE_URL = "/"
    # Specific differentiation
    if "d:" in WRITABLE_DIR or "D:" in WRITABLE_DIR:
        USE_REDIS = True
        DEBUG = True
    elif "c:" in WRITABLE_DIR or "C:" in WRITABLE_DIR:
        USE_REDIS = False
        DEBUG = True
elif "131.174" in hst:
    # Configuration within the Radboud University environment (AppleJack)
    APP_PREFIX = ""             # Was: "passim/"
    #admin.site.site_url = '/'   # Was: '/passim'
    ADMIN_SITE_URL = "/"
    USE_REDIS = True
elif "/var/www" in WRITABLE_DIR:
    # New configuration of http://corpus-studio-web.cttnww-meertens.surf-hosted.nl/passim
    APP_PREFIX = "passim/"
    #admin.site.site_url = '/passim'
    ADMIN_SITE_URL = "/passim"
    USE_REDIS = True
else:
    APP_PREFIX = "dd/"
    #admin.site.site_url = '/dd'
    ADMIN_SITE_URL = "/dd"

# NOTE: change admin.site.site_url in admin.py if needed

# FORCE_SCRIPT_NAME = admin.site.site_url

DATA_UPLOAD_MAX_NUMBER_FIELDS = None
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880

BLOCKED_IPS = ['40.77.167.57',      '161.35.188.242',
               '46.229.168.133',    '54.202.172.244',
               '88.198.17.136',     '34.222.29.95',
               '157.55.39.235',     '37.9.13.199',
               '157.55.39.199',     '61.119.158.79',
               '54.36.148.',        '54.36.149.'
               '45.146.164.110',    '64.227.148.101'
               ]
   

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '561c5400-4ebf-4e45-a2ec-12d856638e45'

ALLOWED_HOSTS = ['localhost', 'applejack.science.ru.nl', 'passim.rich.ru.nl', 'testserver', '131.174.114.236', 'dev.passim.rich.ru.nl' ]

# For django-plotly-dash:
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Caching
if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:7779/1",
            "TIMEOUT": None,
            "OPTIONS": { "CLIENT_CLASS": "django_redis.client.DefaultClient", }
            },
        "select2": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:7779/2",
            "TIMEOUT": None,
            "OPTIONS": { "CLIENT_CLASS": "django_redis.client.DefaultClient", }
            }
        }
    # Set the cache backend to select2
    SELECT2_CACHE_BACKEND = 'select2'
# TESTING PURPOSES: SELECT2_JS = "basic/scripts/select2.js"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'reportlab',
    # 'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    # Add your apps here to enable them
    'django_select2',
    'passim.basic',
    'passim.approve',
    'passim.bible',
    'passim.cms',
    'passim.reader',
    'passim.seeker',
    'passim.dct',
    'passim.stemma',
    'passim.enrich',
    'passim.plugin'
]

# MIDDLEWARE_CLASSES = [
MIDDLEWARE = [
    'passim.utils.BlockedIpMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'passim.urls'

default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'passim/templates')],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            "loaders": default_loaders if DEBUG else cached_loaders,
        },
    },
]

WSGI_APPLICATION = 'passim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(WRITABLE_DIR, 'passim.db'),
        'TEST': {
            'NAME': os.path.join(WRITABLE_DIR, 'passim-test.db'),
            },
        'OPTIONS': {'timeout': 50}
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
if ("/var/www" in WRITABLE_DIR and not bUseTunnel):
    STATIC_URL = "/" + APP_PREFIX + "static/"

STATIC_ROOT = os.path.abspath(os.path.join("/", posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))))
